// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTilFVKdDstvqYcNWT-h69RvqvZ_zShkg',
    appId: '1:471119169821:web:11e6c28ec9f5124f8e39f4',
    messagingSenderId: '471119169821',
    projectId: 'sneakimycare',
    authDomain: 'sneakimycare.firebaseapp.com',
    storageBucket: 'sneakimycare.firebasestorage.app',
    measurementId: 'G-M5LCYNRDTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgCgoBPWRMna1OogXPbWKIJclQczHgxY',
    appId: '1:471119169821:android:f0a3732b6c522f7e8e39f4',
    messagingSenderId: '471119169821',
    projectId: 'sneakimycare',
    storageBucket: 'sneakimycare.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxUGX5D6CwKDCE6nhhsdQa3mFwVhL2zpI',
    appId: '1:471119169821:ios:aab8f63d905fe0708e39f4',
    messagingSenderId: '471119169821',
    projectId: 'sneakimycare',
    storageBucket: 'sneakimycare.firebasestorage.app',
    androidClientId: '471119169821-e6vi39una53oim5su6rbrltdmpp02n6l.apps.googleusercontent.com',
    iosClientId: '471119169821-9c09l3dafih6odlvip0evlt2j9ckhkvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerCareApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxUGX5D6CwKDCE6nhhsdQa3mFwVhL2zpI',
    appId: '1:471119169821:ios:aab8f63d905fe0708e39f4',
    messagingSenderId: '471119169821',
    projectId: 'sneakimycare',
    storageBucket: 'sneakimycare.firebasestorage.app',
    androidClientId: '471119169821-e6vi39una53oim5su6rbrltdmpp02n6l.apps.googleusercontent.com',
    iosClientId: '471119169821-9c09l3dafih6odlvip0evlt2j9ckhkvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTilFVKdDstvqYcNWT-h69RvqvZ_zShkg',
    appId: '1:471119169821:web:649a42390c10539e8e39f4',
    messagingSenderId: '471119169821',
    projectId: 'sneakimycare',
    authDomain: 'sneakimycare.firebaseapp.com',
    storageBucket: 'sneakimycare.firebasestorage.app',
    measurementId: 'G-98QEGY93Y6',
  );
}
